[package]
name = "image-gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.23", default-features = false }

[dev-dependencies]
assert_approx_eq = "1.1.0"
image = { version = "0.23", default-features = false, features = ["png"] }